export const payload_version: number = 3;
export const MODULE_ID = "dnd-model";
export const LIGHT_SPELL_FLAG_KEY = "lightSpell";
export const GUIDING_BOLT_FLAG_KEY = "guidingBoltNextAttack";
export const RANDOM_SPELL_EXCLUSIONS_SETTING_KEY = "randomSpellExclusions";
export const DEFAULT_RANDOM_SPELL_EXCLUSIONS = ["thaumaturgy", "mage hand", "prestidigitation"];
export const ROLLOUT_STATE_FLAG_KEY = "rolloutState";
export const REPEAT_TARGET_SPELLS = new Set(["magic missile", "eldritch blast", "scorching ray"]);
export const RANGE_POSITIONS_CACHE_MAX_ENTRIES = 2000;
